configfile: "config/config.yaml"

include: "rules/files_prep.smk"
include: "rules/alignment.smk"
include: "rules/QC.smk"
include: "rules/analysis.smk"
include: "rules/variant_call_phasing.smk"
include: "rules/ASE.smk"
	
SMP = [0]

myoutput=list()

if "gex_bulk" in config["tech"]:
    myoutput.append(expand("results/{tec}/ASE{chrom}_bulk",chrom=config["chromosomes_to_phase"],tec="gex_bulk"))
if "atac" in config["tech"]:
    myoutput.append(expand("results/{tec}/ASE{chrom}",chrom=config["chromosomes_to_phase"],tec="atac"))
if "gex" in config["tech"]:
    myoutput.append(expand("results/{tec}/ASE{chrom}",chrom=config["chromosomes_to_phase"],tec="gex"))

#rules and checkpoints 

rule all:
    input:
        myoutput,
        expand("results/phased/chr{chrom}_phased.vcf.gz",chrom=config["chromosomes_to_phase"])
